FROM alpine:3.24.1

RUN apk update && \
    apk add --no-cache \
        python3 \
        py3-fastapi \
        py3-uvicorn \
        py3-jinja2 \
        py3-multipart \
        py3-cryptography \
        py3-requests \
        py3-httpx

WORKDIR /app

COPY run_frontend.py .
COPY core/ ./core/
COPY frontend/ ./frontend/

RUN chmod +x run_frontend.py

ENV GATEWAY_CONFIG="/data/config.json" \
    UI_CONFIG="/data/ui_config.json"

EXPOSE 8443

CMD ["python3", "run_frontend.py"]
