services:

  smtp:
    build:
      context: .
      dockerfile: build.alpine
      network: host
    container_name: smtp
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    network_mode: host
    volumes:
      - ./queue:/tmp/pushover_queue
      - ./config.json:/config.json
    environment:
      PYTHONUNBUFFERED: 1
      GATEWAY_CONFIG: /config.json
    command: python3 /smtp_pushover.py
